sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_038847a4f507_key -iv $encrypted_038847a4f507_iv -in multi-k8s-386305-5891f8c6353b.json.enc -out multi-k8s-386305-5891f8c6353b.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-386305-5891f8c6353b.json
  - gcloud config set project multi-k8s-386305
  - gcloud config set compute/zone asia-south1-a
  - gcloud container clusters get-credentials cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t hillolchakrabarty40/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker build -t hillolchakrabarty40/react-test -f ./client/Dockerfile.dev ./client

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
